-- AlterTable
ALTER TABLE "Complaint" ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "udpatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
